# Generated by Django 5.1.6 on 2025-02-11 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=16, null=True, unique=True, verbose_name='شناسه کاربر')),
                ('user_name', models.CharField(blank=True, max_length=65, null=True, verbose_name='نام کاربر')),
                ('email', models.CharField(blank=True, max_length=65, verbose_name='ایمیل کاربر')),
                ('password', models.CharField(blank=True, max_length=65, null=True, verbose_name='رمزعبور کاربر')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد کاربر')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروز رسانی کاربر')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربر ها',
            },
        ),
    ]
