# Generated by Django 5.1.5 on 2025-02-03 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_id', models.CharField(blank=True, max_length=16, null=True, unique=True, verbose_name='شناسه انبار')),
                ('inventory_name', models.CharField(blank=True, max_length=65, null=True, verbose_name='نام انبار')),
                ('inventory_capacity', models.CharField(blank=True, max_length=65, verbose_name='ظرفیت انبار')),
                ('inventory_location', models.CharField(blank=True, max_length=65, null=True, verbose_name='موقعیت فیزیکی انبار')),
                ('personnal_id', models.CharField(blank=True, max_length=65, null=True, verbose_name='متصدی انبار')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد انبار')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروز رسانی انبار')),
            ],
            options={
                'verbose_name': 'انبار',
                'verbose_name_plural': 'انبار ها',
            },
        ),
    ]
