# Generated by Django 5.1.6 on 2025-02-11 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='inventory_category',
            field=models.CharField(blank=True, max_length=65, null=True, verbose_name='دسته بندی انبار'),
        ),
    ]
