# Generated by Django 5.1.6 on 2025-02-11 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventory_inventory_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='inventory_id',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='شناسه انبار'),
        ),
    ]
