# Generated by Django 5.1.6 on 2025-02-12 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_inventory_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory_manager',
            name='inventory_id',
        ),
    ]
