# Generated by Django 5.1.5 on 2025-02-03 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=255, unique=True, verbose_name='نام بخش')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'واحد سازمان',
                'verbose_name_plural': 'واحد های سازمان',
            },
        ),
        migrations.CreateModel(
            name='CorporatePersonnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personnal_first_name', models.CharField(max_length=100, verbose_name='نام')),
                ('personnal_last_name', models.CharField(max_length=100, verbose_name='نام خانوادگی')),
                ('personnal_email', models.EmailField(max_length=254, unique=True, verbose_name='ایمیل')),
                ('personnal_phone_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='شماره تلفن')),
                ('personnal_position', models.CharField(max_length=255, verbose_name='سمت شغلی')),
                ('personnal_date_hired', models.DateField(verbose_name='تاریخ استخدام')),
                ('personnal_type_status', models.CharField(choices=[('نیروی ثابت', 'نیروی ثابت'), ('نیروی شناور', 'نیروی شناور')], default='active', max_length=20, verbose_name='نوع استخدام')),
                ('personnal_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='حقوق')),
                ('personnal_address', models.TextField(blank=True, null=True, verbose_name='کد ملی')),
                ('personnal_birth_date', models.DateField(blank=True, null=True, verbose_name='تاریخ تولد')),
                ('personnal_emergency_contact', models.CharField(blank=True, max_length=255, null=True, verbose_name='تماس اضطراری')),
                ('personnal_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='personnal.department', verbose_name='بخش')),
            ],
            options={
                'verbose_name': 'نیروی سازمان',
                'verbose_name_plural': 'پرسنل سازمان',
            },
        ),
    ]
