# Generated by Django 5.1.6 on 2025-02-12 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='corporatepersonnel',
            name='personal_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='شناسه پرسنلی'),
        ),
        migrations.AddField(
            model_name='corporatepersonnel',
            name='personnal_melli_code',
            field=models.TextField(blank=True, null=True, verbose_name='کد ملی'),
        ),
        migrations.AddField(
            model_name='department',
            name='department_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='شناسه دپارتمان'),
        ),
        migrations.AlterField(
            model_name='corporatepersonnel',
            name='personnal_address',
            field=models.TextField(blank=True, null=True, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='corporatepersonnel',
            name='personnal_email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='corporatepersonnel',
            name='personnal_first_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='corporatepersonnel',
            name='personnal_last_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='department',
            name='department_name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='نام بخش'),
        ),
    ]
