# Generated by Django 5.1.6 on 2025-02-12 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnal', '0002_corporatepersonnel_personal_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corporatepersonnel',
            name='personnal_department',
        ),
        migrations.AddField(
            model_name='corporatepersonnel',
            name='personnal_department_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='بخش'),
        ),
    ]
