# Generated by Django 5.1.6 on 2025-02-12 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personnal', '0003_remove_corporatepersonnel_personnal_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corporatepersonnel',
            name='personnal_email',
        ),
    ]
