# Generated by Django 5.1.6 on 2025-02-12 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnal', '0004_remove_corporatepersonnel_personnal_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corporatepersonnel',
            name='personnal_type_status',
            field=models.CharField(blank=True, default='active', max_length=20, null=True, verbose_name='نوع استخدام'),
        ),
    ]
