# Generated by Django 5.1.6 on 2025-02-12 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnal', '0005_alter_corporatepersonnel_personnal_type_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corporatepersonnel',
            name='personnal_date_hired',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ استخدام'),
        ),
        migrations.AlterField(
            model_name='corporatepersonnel',
            name='personnal_position',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='سمت شغلی'),
        ),
    ]
